Tested version
bobgromozeka/yp-diploma1 pull request #2
Opened 2023-08-13 14:27 UTC by bobgromozeka

2023-08-14 15:54 UTC, rktkov requested changes

2023-08-14 15:54 UTC, rktkov commented on internal/storage/storage.go
> +type Storage interface {
Стоит разделит интерфейс между сущностями - пользователя, заказа и может быть даже баланса бонусных балов.

2023-08-14 15:54 UTC, rktkov commented on internal/server/handlers/orders/create.go
> +		userID, userIDErr := jwt.GetUserID(r.Context())
вот можно в мидлварю вынести

2023-08-14 15:54 UTC, rktkov commented on internal/storage/pg.go
> +	existingOrder, existingOrderErr := s.GetOrder(ctx, number)
Вот нужно в транзакцию 2 запроса объединить (чтобы между запросом номера заказа и созданием нового никто не вклинился в процесс)

2023-08-14 15:54 UTC, rktkov commented on internal/storage/pg.go
> +	tx, txErr := s.db.BeginTx(ctx, nil)
Кажется транзакцию надо уже на уровне запроса баланса создатьва.

2023-08-14 15:54 UTC, rktkov commented on internal/server/server.go
> +	if wg != nil {
я бы это в  defer обернул и перенес бы в начало метода. Потому что код не выполнится если у тебя фаталы из 97 или 105 строки вызовутся.

2023-08-14 15:54 UTC, rktkov commented on internal/accrual/accrual.go
> +	wg.Done()
А почему в сервере на nil  есть проверка, а тут нет? и тот же совет про defer

2023-08-16 19:51 UTC, bobgromozeka commented on internal/storage/storage.go
> +type UsersStorage interface {
Я поделил Storage на логические интерфейсы по сущностям. Но не уверен что в этом есть большой смысл в данном случае, потому что у меня некоторые методы обращаются сразу к 2-м сущностям (обновление заказа, например). Стоит ли рефакторить взаимодействие с хранилищем ? Если да, то одним из вариантов видится подход, когда всю функции DAL собирают в один большой интерфейс (querier) и делают только простые операции в каждой (по 1 запросу за раз), а менеджмент транзакций оставляют для BLL, но это частичное протекание деталей реализации хранилища. Но в golang это считается ОК, если я не ошибаюсь.

2023-08-24 14:15 UTC, rktkov requested changes
Выглядит хорошо. Жду интеграционных тестов для финального апрува.

2023-08-24 14:15 UTC, rktkov commented on internal/storage/storage.go
> +type UsersStorage interface {
Я за такой подход в разделении и ничего, что один метод работает с несколькими сущностями. А по подводу транзакции - можно и "хранилище независимой" оберточку  сделать, которую использовать дальше в запросах передавая одним из аргументов метода.

2023-09-29 13:40 UTC, merged